@host=https://localhost:7238

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@email.com",
    "password": "password"
}