@host=https://localhost:7238
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3M2QyOGQ3Yy03NWQ0LTQzYjctODNkZS1iMDEwYjQyZmFhNTgiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNmZjYzQyNDAtNWM3MC00YmZiLTgwM2ItZWE3NWRlNTc4M2NkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUmVxdWVzdGVyIiwiZXhwIjoxNzIyMDI1MjczLCJpc3MiOiJJbnZlbkVhc2UiLCJhdWQiOiJJbnZlbkVhc2UifQ.or_0DOvtYNq5HyHSqfui10CFOlu5A7DU7B3gIuUYpB4
@itemId=362c0a18-c443-465b-ac99-8b55cf30ae08

DELETE {{host}}/items/{{itemId}}
Content-Type: application/json
Authorization: Bearer {{token}}