@host=https://localhost:7238
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NTViMmU2Ni0yYTgzLTRjYzYtYjMyOS0xMDRjZmY5OGMyMzAiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiYjc1NTJlNGMtM2U5OS00ODA3LWEzYzEtZjM2MmE2NzI1NDcxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUmVxdWVzdGVyIiwiZXhwIjoxNzIxOTUyNjQzLCJpc3MiOiJJbnZlbkVhc2UiLCJhdWQiOiJJbnZlbkVhc2UifQ.VbTp8oS0AYx6oVjwEN3FlTpH_HlJjOXdkJ5hzyqWCRw

GET {{host}}/items
Content-Type: application/json
Authorization: Bearer {{token}}